### ISSUE TITLE
Open source?

### ISSUE THREAD

**Issue by Its-Haze** [Frostipanda/Once-Human-Midi-Player#1]
I'd like to verify the integrity of the software, since it's needed to be ran as and administrator.
Is there a reason for not publishing the code in this repo?

**Comment by Frostipanda** [comment]
> I'd like to verify the integrity of the software, since it's needed to be ran as and administrator. Is there a reason for not publishing the code in this repo?

The code is readily available for the current python version when you download it, all .py and resources are unencrypted.

I am however in the process of converting the program over to C# and I am adding the .cs code to the repo as we speak for that.
